server:
  port: 9030
  servlet:
    context-path: /api-service


spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: 'jdbc:mysql://169.254.169.254:3306/mysql'
    driverClassName: com.mysql.cj.jdbc.Driver
    username:
    password: password

logging:
  level:
    org:
      springframework:
        web: INFO
