server:
  port: 9030
  servlet:
    context-path: /api-service


spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://mysql:3306/demo
    username: root
    password: password

logging:
  level:
    org:
      springframework:
        web: INFO
