server:
  port: 9030
  servlet:
    context-path: /api-service


#spring:
 # datasource:
  #  url: 'jdbc:sqlserver://sql-azu-e2-acs-dev-raiq.database.windows.net:1433;database=sql-azu-e2-acs-dev-raiq-hrms-nonprod;user=${devDbUser}@sql-azu-e2-acs-dev-raiq;password={${devDbPassword}};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;'
   # driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #username: ${devDbUser}
    #password: ${devDbPassword}

logging:
  level:
    org:
      springframework:
        web: INFO
