server:
  port: 9030
  servlet:
    context-path: /api-service
spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://mysql-nagp:3306/demoDb
    username: myUser
    password: cGFzc3dvcmQ=

logging:
  level:
    org:
      springframework:
        web: INFO
