apiVersion: v1
kind: Service
metadata:
  name: mysql-nagp
  labels:
    app: mysql-nagp
spec:
  clusterIP: None
  selector:
    app: mysql-nagp
  ports:
    - name: tcp
      protocol: TCP
      port: 3306